I'm sorry, but an uncaught exception occurred.

While parsing E:\renpy\PJ-School_git\venti-mesi/game/options.rpy.
ScriptError: Name (u'/home/tom/ab/renpy/renpy/common/000atl.rpy', 1434348405, 52) is defined twice, at renpy/common/000atl.rpy:25 and renpy/common/000atl.rpy:25.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "E:\renpy\PJ-School_git\venti-mesi\renpy\bootstrap.py", line 281, in bootstrap
    renpy.main.main()
  File "E:\renpy\PJ-School_git\venti-mesi\renpy\main.py", line 356, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "E:\renpy\PJ-School_git\venti-mesi\renpy\script.py", line 185, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "E:\renpy\PJ-School_git\venti-mesi\renpy\script.py", line 660, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "E:\renpy\PJ-School_git\venti-mesi\renpy\script.py", line 340, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name (u'/home/tom/ab/renpy/renpy/common/000atl.rpy', 1434348405, 52) is defined twice, at renpy/common/000atl.rpy:25 and renpy/common/000atl.rpy:25.

Windows-8-6.2.9200
Ren'Py 6.99.5.602
 
